// ============================================================
//  JAMB CBT 2026 — SET 1
//  Use of English : 60 questions (section objects)
//  Biology        : 40 questions (flat array)
//  Chemistry      : 40 questions (flat array)
//  Physics        : 40 questions (flat array)
//
//  Question format:
//    id          – unique string
//    question    – question text
//    options     – { A:"...", B:"...", C:"...", D:"..." }
//    answer      – "A" | "B" | "C" | "D"
//    explanation – explanation string
// ============================================================


// ── USE OF ENGLISH ───────────────────────────────────────────
DB["Use of English"][1] = [

  // SECTION 1 – Comprehension Passage 1
  {
    section: "Comprehension",
    passage: `Nigeria's education system has undergone significant transformation since independence in 1960. In the early years, education was largely driven by missionary institutions and colonial structures, with limited access for the majority of Nigerians. However, following independence, successive governments recognised education as a tool for national development and began investing in schools, colleges, and universities across the country.\n\nDespite these efforts, the Nigerian education system continues to face enormous challenges. Inadequate funding, dilapidated infrastructure, poorly motivated teachers, and examination malpractice remain persistent problems. Many public schools lack basic facilities such as libraries, laboratories, and furniture. As a result, the quality of graduates produced has declined steadily, raising concerns among employers and policymakers alike.\n\nExperts have argued that without a fundamental restructuring of the education sector — one that prioritises funding, teacher welfare, and curriculum relevance — Nigeria risks producing a generation ill-equipped to drive the nation's development. The solution, they insist, lies not in cosmetic reforms but in bold, sustained investment backed by political will.`,
    questions: [
      {
        id: "en1_1",
        question: "According to the passage, what drove education in Nigeria's early post-independence years?",
        options: { A: "Government universities", B: "Missionary institutions and colonial structures", C: "Private investors and corporations", D: "International aid organisations" },
        answer: "B",
        explanation: "The passage directly states 'education was largely driven by missionary institutions and colonial structures' in the early years."
      },
      {
        id: "en1_2",
        question: "The word 'dilapidated' as used in the passage most nearly means",
        options: { A: "Well-furnished", B: "Recently constructed", C: "Fallen into disrepair", D: "Poorly designed" },
        answer: "C",
        explanation: "Dilapidated means in a state of severe deterioration due to neglect — describing infrastructure that has decayed over time."
      },
      {
        id: "en1_3",
        question: "Which of the following is NOT mentioned as a challenge facing Nigerian education?",
        options: { A: "Inadequate funding", B: "Examination malpractice", C: "Lack of qualified graduates", D: "Poorly motivated teachers" },
        answer: "C",
        explanation: "The passage mentions inadequate funding, examination malpractice, and poorly motivated teachers. It says quality of graduates has declined — it never says there is a lack of qualified graduates."
      },
      {
        id: "en1_4",
        question: "The experts cited believe that the solution to Nigeria's education crisis lies in",
        options: { A: "Importing foreign teachers and curricula", B: "Closing underperforming public schools", C: "Bold, sustained investment backed by political will", D: "Cosmetic reforms and gradual policy changes" },
        answer: "C",
        explanation: "The final paragraph states 'The solution, they insist, lies not in cosmetic reforms but in bold, sustained investment backed by political will.' Option D is the direct opposite."
      },
      {
        id: "en1_5",
        question: "The tone of the passage can best be described as",
        options: { A: "Celebratory and optimistic", B: "Analytical and concerned", C: "Satirical and humorous", D: "Indifferent and detached" },
        answer: "B",
        explanation: "The writer presents facts, identifies serious problems, and calls for solutions in a measured, serious manner — making the tone analytical and concerned throughout."
      }
    ]
  },

  // SECTION 2 – Comprehension Passage 2
  {
    section: "Comprehension",
    passage: `Climate change has emerged as one of the most pressing challenges of the twenty-first century, and Africa stands at the frontline of its devastating consequences. Despite contributing less than four percent of global greenhouse gas emissions, the continent bears a disproportionate burden of the effects. Rising temperatures, prolonged droughts, erratic rainfall, and devastating floods have become increasingly common across the region, threatening food security, water supply, and human lives.\n\nIn Nigeria, the effects are already visible. The Lake Chad Basin, once one of the largest freshwater bodies in the world, has shrunk by approximately ninety percent over the past five decades due to a combination of climate change and human activities. Communities that once depended on the lake for fishing and farming have been displaced, fuelling poverty and conflict in the region. Coastal cities like Lagos also face the growing threat of flooding and sea-level rise, which endanger lives and destroy infrastructure worth billions of naira annually.\n\nAfrican leaders and environmental experts have repeatedly called for developed nations to honour their financial commitments to climate adaptation funds. They argue that justice demands that those most responsible for the crisis bear the greatest cost of addressing it. Until such commitments are met, Africa will continue to suffer the consequences of a problem it did little to create.`,
    questions: [
      {
        id: "en1_6",
        question: "According to the passage, Africa contributes what percentage of global greenhouse gas emissions?",
        options: { A: "Less than ten percent", B: "Less than four percent", C: "Approximately fifty percent", D: "More than twenty percent" },
        answer: "B",
        explanation: "The passage explicitly states Africa contributes 'less than four percent of global greenhouse gas emissions.'"
      },
      {
        id: "en1_7",
        question: "The word 'disproportionate' as used in the passage means",
        options: { A: "Equal and fair", B: "Matching exactly", C: "Larger than what is justified or expected", D: "Smaller than average" },
        answer: "C",
        explanation: "Disproportionate means out of proportion relative to something else. Africa bears a burden far greater than its tiny contribution justifies."
      },
      {
        id: "en1_8",
        question: "According to the passage, what has caused the shrinking of Lake Chad?",
        options: { A: "Climate change alone", B: "Human activities alone", C: "A combination of climate change and human activities", D: "Government policies on water management" },
        answer: "C",
        explanation: "The passage states Lake Chad shrunk 'due to a combination of climate change and human activities' — neither factor alone is the correct answer."
      },
      {
        id: "en1_9",
        question: "Which consequence of climate change in Nigeria is mentioned in the passage?",
        options: { A: "Desertification in the south", B: "Flooding and sea-level rise threatening coastal cities", C: "Destruction of oil pipelines", D: "Mass emigration of farmers to urban areas" },
        answer: "B",
        explanation: "The passage specifically mentions 'Coastal cities like Lagos also face the growing threat of flooding and sea-level rise.' None of the other options appear in the passage."
      },
      {
        id: "en1_10",
        question: "The main argument of African leaders and experts as presented in the passage is that",
        options: { A: "Africa should develop its own climate funds", B: "Developed nations must honour financial commitments to climate adaptation", C: "Nigeria should relocate communities away from Lake Chad", D: "Africa must reduce its greenhouse gas emissions immediately" },
        answer: "B",
        explanation: "The final paragraph states leaders 'called for developed nations to honour their financial commitments to climate adaptation funds' — this is their central argument."
      }
    ]
  },

  // SECTION 3 – Cloze Test
  {
    section: "Cloze Test",
    passage: `The rapid advancement of technology has greatly (11)___ the lives of young Nigerians. Today, millions of youths have (12)___ to smartphones and the internet, tools that were considered (13)___ just two decades ago. Through these devices, young people can now (14)___ information, connect with others across the globe, and even (15)___ a living without leaving their homes. However, this technological (16)___ has not come without its challenges. Many youths spend (17)___ amounts of time on social media, often at the (18)___ of their studies and productivity. Experts have therefore (19)___ that while technology should be embraced, it must be used with (20)___ and purpose.`,
    questions: [
      { id:"en1_11", question:"…has greatly ___ the lives of young Nigerians", options:{A:"Destroyed",B:"Transformed",C:"Ignored",D:"Complicated"}, answer:"B", explanation:"Transformed means changed significantly for the better — fitting the positive opening tone. Complicated is negative and contradicts the passage." },
      { id:"en1_12", question:"millions of youths have ___ to smartphones and the internet", options:{A:"Addiction",B:"Resistance",C:"Access",D:"Exposure"}, answer:"C", explanation:"Have access to is the correct collocation — meaning they can obtain and use these tools." },
      { id:"en1_13", question:"tools that were considered ___ just two decades ago", options:{A:"Essential",B:"Primitive",C:"Luxuries",D:"Dangerous"}, answer:"C", explanation:"Two decades ago smartphones were rare and expensive — considered luxuries. Primitive wrongly describes the tools as basic." },
      { id:"en1_14", question:"young people can now ___ information", options:{A:"Produce",B:"Access",C:"Destroy",D:"Sell"}, answer:"B", explanation:"Access information is the standard, natural collocation in formal English — meaning to retrieve or obtain information from a source." },
      { id:"en1_15", question:"and even ___ a living without leaving their homes", options:{A:"Demand",B:"Spend",C:"Earn",D:"Borrow"}, answer:"C", explanation:"Earn a living is the correct fixed expression in English meaning to make money through work." },
      { id:"en1_16", question:"this technological ___ has not come without its challenges", options:{A:"Failure",B:"Revolution",C:"Collapse",D:"Experiment"}, answer:"B", explanation:"Technological revolution refers to the major, rapid change brought about by technology." },
      { id:"en1_17", question:"Many youths spend ___ amounts of time on social media", options:{A:"Limited",B:"Productive",C:"Excessive",D:"Reasonable"}, answer:"C", explanation:"The context is negative — spending too much time at the expense of studies. Excessive is the only option that conveys this harmful overuse." },
      { id:"en1_18", question:"often at the ___ of their studies and productivity", options:{A:"Benefit",B:"Improvement",C:"Expense",D:"Foundation"}, answer:"C", explanation:"At the expense of is a fixed English idiom meaning something is sacrificed or harmed." },
      { id:"en1_19", question:"Experts have therefore ___ that while technology should be embraced", options:{A:"Denied",B:"Forgotten",C:"Argued",D:"Prevented"}, answer:"C", explanation:"Experts have argued is the natural, formal collocation for presenting a position or recommendation." },
      { id:"en1_20", question:"it must be used with ___ and purpose", options:{A:"Confusion",B:"Caution",C:"Speed",D:"Freedom"}, answer:"B", explanation:"Used with caution means used carefully and wisely — fitting expert advice perfectly." }
    ]
  },

  // SECTION 4 – Lexis & Structure
  {
    section: "Lexis & Structure",
    questions: [
      { id:"en1_21", question:"Choose the word NEAREST in meaning to AUDACIOUS", options:{A:"Timid",B:"Daring",C:"Careful",D:"Honest"}, answer:"B", explanation:"Audacious means showing willingness to take bold risks — closest to daring. Timid is its antonym." },
      { id:"en1_22", question:"Choose the word OPPOSITE in meaning to BENEVOLENT", options:{A:"Generous",B:"Charitable",C:"Malevolent",D:"Indifferent"}, answer:"C", explanation:"Benevolent means well-meaning and kind. Its direct antonym is malevolent — wishing to do evil." },
      { id:"en1_23", question:"Choose the word NEAREST in meaning to ELOQUENT", options:{A:"Silent",B:"Confused",C:"Articulate",D:"Aggressive"}, answer:"C", explanation:"Eloquent means fluent and persuasive in speech or writing. Articulate shares this meaning." },
      { id:"en1_24", question:"Choose the word OPPOSITE in meaning to DILIGENT", options:{A:"Hardworking",B:"Industrious",C:"Lazy",D:"Focused"}, answer:"C", explanation:"Diligent means careful and hard-working. Its antonym is lazy." },
      { id:"en1_25", question:"Choose the correct option: \"The governor, together with his aides, ___ arrived at the venue.\"", options:{A:"Have",B:"Were",C:"Has",D:"Are"}, answer:"C", explanation:"When 'together with' joins a singular subject to another noun, the verb agrees with the original subject. The governor is singular — so 'has' is correct." },
      { id:"en1_26", question:"Identify the figure of speech: \"The wind whispered secrets through the trees.\"", options:{A:"Simile",B:"Hyperbole",C:"Personification",D:"Metaphor"}, answer:"C", explanation:"Whispered is a human action attributed to the wind — a non-human thing. Attributing human qualities to non-human subjects is personification." },
      { id:"en1_27", question:"\"After the scandal, the politician decided to lie low.\" This means he decided to", options:{A:"Sleep on the floor",B:"Tell lies to everyone",C:"Avoid attention and stay out of sight",D:"Resign from his position"}, answer:"C", explanation:"Lie low is an idiom meaning to keep a low profile — avoid drawing attention, especially during a difficult period." },
      { id:"en1_28", question:"Choose the word NEAREST in meaning to SYCOPHANT", options:{A:"Critic",B:"Flatterer",C:"Leader",D:"Opponent"}, answer:"B", explanation:"A sycophant acts obsequiously toward important people to gain favour — a flatterer or yes-man." },
      { id:"en1_29", question:"Choose the grammatically CORRECT sentence:", options:{A:"Neither of the boys have submitted their assignments.",B:"Neither of the boys has submitted his assignment.",C:"Neither of the boys have submitted his assignment.",D:"Neither of the boys has submitted their assignments."}, answer:"B", explanation:"Neither takes a singular verb (has) and singular pronoun (his) in formal English. Both agreements are correctly applied only in B." },
      { id:"en1_30", question:"Choose the word OPPOSITE in meaning to VERBOSE", options:{A:"Talkative",B:"Wordy",C:"Concise",D:"Loud"}, answer:"C", explanation:"Verbose means using more words than needed. Its antonym is concise — expressing much in few words." },
      { id:"en1_31", question:"\"She has a heart of gold.\" This means she is", options:{A:"Wealthy and powerful",B:"Extremely kind and generous",C:"Cold and unfeeling",D:"Proud of her achievements"}, answer:"B", explanation:"A heart of gold is a fixed idiom meaning someone is exceptionally kind and generous." },
      { id:"en1_32", question:"Choose the correct reported speech for: \"He said, 'I am going to Lagos tomorrow.'\"", options:{A:"He said that he is going to Lagos tomorrow.",B:"He said that he was going to Lagos the following day.",C:"He said that I am going to Lagos tomorrow.",D:"He said that he will go to Lagos tomorrow."}, answer:"B", explanation:"With a past reporting verb (said), 'am going' shifts to 'was going', 'tomorrow' shifts to 'the following day', and 'I' shifts to 'he'. All three changes are correctly applied only in B." },
      { id:"en1_33", question:"Choose the word NEAREST in meaning to EPHEMERAL", options:{A:"Eternal",B:"Permanent",C:"Transient",D:"Consistent"}, answer:"C", explanation:"Ephemeral means lasting a very short time. Transient shares this meaning — existing only briefly." },
      { id:"en1_34", question:"Identify the figure of speech: \"I have told you a million times to keep quiet!\"", options:{A:"Personification",B:"Simile",C:"Hyperbole",D:"Alliteration"}, answer:"C", explanation:"A million times is a deliberate exaggeration for emphasis. Deliberate exaggeration for effect is hyperbole." },
      { id:"en1_35", question:"Choose the grammatically CORRECT sentence:", options:{A:"Each of the students have their own textbook.",B:"Each of the students has their own textbook.",C:"Each of the students has his own textbook.",D:"Each of the students have his own textbook."}, answer:"C", explanation:"Each is always singular — it takes a singular verb (has) and singular pronoun (his) in formal English." },
      { id:"en1_36", question:"Choose the word OPPOSITE in meaning to INDIGENOUS", options:{A:"Native",B:"Local",C:"Foreign",D:"Traditional"}, answer:"C", explanation:"Indigenous means originating naturally in a place. Its antonym is foreign — belonging to or coming from elsewhere." },
      { id:"en1_37", question:"\"By the time we arrived, the meeting ___ already started.\"", options:{A:"Has",B:"Have",C:"Had",D:"Was"}, answer:"C", explanation:"'By the time we arrived' signals one past event happening before another. This requires the past perfect tense: had already started." },
      { id:"en1_38", question:"Choose the word NEAREST in meaning to METICULOUS", options:{A:"Careless",B:"Thorough",C:"Hasty",D:"Reckless"}, answer:"B", explanation:"Meticulous means showing great attention to detail and care. Thorough shares this meaning." },
      { id:"en1_39", question:"Which sentence uses the apostrophe CORRECTLY?", options:{A:"The childrens' books are on the table.",B:"The children's books are on the table.",C:"The childrens books are on the table.",D:"The children's book's are on the table."}, answer:"B", explanation:"Children is an irregular plural — it does not end in s. To show possession, add apostrophe + s: children's." },
      { id:"en1_40", question:"Choose the word OPPOSITE in meaning to LOQUACIOUS", options:{A:"Talkative",B:"Garrulous",C:"Verbose",D:"Taciturn"}, answer:"D", explanation:"Loquacious means tending to talk a great deal. Its antonym is taciturn — reserved, saying very little." }
    ]
  },

  // SECTION 5 – Oral English
  {
    section: "Oral English",
    questions: [
      { id:"en1_41", question:"Which of the following words has a DIFFERENT vowel sound from the others?", options:{A:"Beat",B:"Seat",C:"Meat",D:"Meant"}, answer:"D", explanation:"Beat, seat, and meat all contain the long vowel sound /iː/. Meant contains the short vowel sound /ɛ/ as in bed — making it the odd one out." },
      { id:"en1_42", question:"In which of the following words is the first letter silent?", options:{A:"Knife",B:"Cat",C:"Book",D:"Run"}, answer:"A", explanation:"In knife, the k is silent — pronounced /naɪf/. Silent k always appears before n at the start of words: knife, know, knock, knee." },
      { id:"en1_43", question:"The word RECORD when used as a NOUN is stressed on", options:{A:"The second syllable (re-CORD)",B:"Both syllables equally",C:"The first syllable (RE-cord)",D:"Neither syllable"}, answer:"C", explanation:"Record follows the noun/verb stress shift pattern. As a NOUN: RE-cord. As a VERB: re-CORD." },
      { id:"en1_44", question:"Which of the following pairs of words are MINIMAL PAIRS?", options:{A:"Cat / car",B:"Ship / sheep",C:"Book / cook",D:"Table / chair"}, answer:"B", explanation:"A minimal pair consists of two words differing by only ONE phoneme. Ship /ʃɪp/ and sheep /ʃiːp/ differ only in the vowel — /ɪ/ versus /iː/." },
      { id:"en1_45", question:"Which of the following words contains the vowel sound /ʌ/ as in cup?", options:{A:"Cool",B:"Book",C:"Blood",D:"Food"}, answer:"C", explanation:"Blood is pronounced /blʌd/ — containing the /ʌ/ vowel despite its spelling. Cool and food have /uː/. Book has /ʊ/." },
      { id:"en1_46", question:"Which correctly describes the consonant sound at the beginning of THIN?", options:{A:"Voiced bilabial plosive",B:"Voiceless dental fricative",C:"Voiced velar nasal",D:"Voiceless alveolar plosive"}, answer:"B", explanation:"The th in thin is /θ/ — tongue near upper teeth, air flows with friction, no vocal cord vibration: voiceless + dental + fricative." },
      { id:"en1_47", question:"In which sentence would the speaker most likely use RISING intonation?", options:{A:"She passed her exams.",B:"Close the door.",C:"Did he call you?",D:"The match ended in a draw."}, answer:"C", explanation:"Rising intonation is used in Yes/No questions. 'Did he call you?' fits this perfectly. Statements and commands use falling intonation." },
      { id:"en1_48", question:"Which of the following words rhymes with PLIGHT?", options:{A:"Plate",B:"Slight",C:"Pleat",D:"Plot"}, answer:"B", explanation:"Plight /plaɪt/ ends with the /aɪt/ sound. Slight /slaɪt/ also ends with /aɪt/ — they rhyme perfectly." },
      { id:"en1_49", question:"The word PERMIT when used as a VERB carries stress on", options:{A:"The first syllable (PER-mit)",B:"Both syllables",C:"The second syllable (per-MIT)",D:"Neither syllable"}, answer:"C", explanation:"As a VERB: per-MIT. As a NOUN: PER-mit. This two-syllable noun/verb stress shift is a consistently tested pattern in JAMB Oral English." },
      { id:"en1_50", question:"Which set of three words all contain the SAME vowel sound?", options:{A:"Cat, car, care",B:"Bed, dead, said",C:"Go, so, toe",D:"Put, cut, but"}, answer:"C", explanation:"Go /gəʊ/, so /səʊ/, and toe /təʊ/ all share the diphthong /əʊ/. Option D mixes /ʊ/ (put) with /ʌ/ (cut, but)." }
    ]
  },

  // SECTION 6 – Novel: The Lekki Headmaster
  {
    section: "Novel – The Lekki Headmaster",
    questions: [
      { id:"en1_51", question:"What is the full name of the central character in The Lekki Headmaster?", options:{A:"Mr. Kabir Adewale",B:"Mr. Adebepo Adewale",C:"Mr. Ikenna Stardom",D:"Mr. Wande Garba"}, answer:"B", explanation:"The protagonist's full name is Mr. Adebepo Adewale, affectionately called Bepo. He is the principal of Stardom Schools in Lekki, Lagos." },
      { id:"en1_52", question:"At the beginning of the novel, Bepo breaks down in tears during", options:{A:"A staff meeting",B:"A parent-teacher association meeting",C:"The school's morning assembly",D:"A private conversation with the Vice Principal"}, answer:"C", explanation:"The novel opens with Bepo weeping uncontrollably during the school's morning assembly — shocking everyone who knew him as a confident, lively figure." },
      { id:"en1_53", question:"What is the name of the school where Bepo serves as principal?", options:{A:"Lekki Academy",B:"Beesway Group of Schools",C:"Fruitful Future Schools",D:"Stardom Schools"}, answer:"D", explanation:"Bepo is the principal of Stardom Schools, an elite institution in the Lekki suburb of Lagos." },
      { id:"en1_54", question:"The central conflict of the novel revolves around Bepo's dilemma of", options:{A:"Whether to report a corrupt colleague to authorities",B:"Whether to relocate to the UK or remain in Nigeria",C:"Whether to resign and start his own school",D:"Whether to accept a promotion or stay as principal"}, answer:"B", explanation:"The heart of the novel is Bepo's agonising decision — leave Nigeria to join his wife and children in the UK, or stay at Stardom Schools and continue his mission." },
      { id:"en1_55", question:"Bepo's wife, who lives in the United Kingdom, is named", options:{A:"Nike",B:"Kike",C:"Seri",D:"Beke"}, answer:"C", explanation:"Bepo's wife is Seri, a nurse in the UK. Nike and Kike are their daughters. Beke Egbin is the school's guidance counsellor — a common trap question." },
      { id:"en1_56", question:"The Vice Principal who steps in during Bepo's breakdown at assembly is", options:{A:"Mrs. Titi",B:"Mrs. Beke Egbin",C:"Mrs. Justus Anabel",D:"Mrs. Grace Apeh"}, answer:"D", explanation:"Mrs. Grace Apeh is Stardom Schools' Vice Principal. She is the first colleague to respond — stepping in to manage the assembly." },
      { id:"en1_57", question:"The 'Japa syndrome' as explored in the novel refers to", options:{A:"The Nigerian tradition of community service",B:"The trend of Nigerians emigrating abroad for better opportunities",C:"A cultural festival celebrated in Lekki",D:"The pressure on students to pass external examinations"}, answer:"B", explanation:"Japa is Yoruba slang meaning to flee or escape. In the novel it refers to the mass emigration of Nigerian professionals to the UK and US in search of better conditions." },
      { id:"en1_58", question:"How many years had Bepo served at Stardom Schools before the events of the novel?", options:{A:"Ten years",B:"Fifteen years",C:"Twenty years",D:"Twenty-four years"}, answer:"D", explanation:"The novel clearly states Bepo had served Stardom Schools for 24 years — earning deep respect and the title The Lekki Headmaster." },
      { id:"en1_59", question:"At the end of the novel, Bepo decides to", options:{A:"Relocate permanently to the United Kingdom",B:"Retire from teaching entirely",C:"Stay in Nigeria and return to his school",D:"Accept a government appointment"}, answer:"C", explanation:"Despite enormous pressure, Bepo chooses Nigeria and his students. He returns to assembly and is lifted shoulder-high by students in celebration." },
      { id:"en1_60", question:"Which best describes the dominant theme of The Lekki Headmaster?", options:{A:"The dangers of corruption in private schools",B:"The conflict between personal ambition and patriotic duty",C:"The importance of religious faith in difficult times",D:"The rivalry between Nigerian and British education systems"}, answer:"B", explanation:"The novel's dominant theme is the tension between personal interests (comfort abroad) and patriotic duty (staying to serve Nigeria). Bepo's final choice affirms the triumph of purpose over personal gain." }
    ]
  }

]; // end Use of English


// ── BIOLOGY ──────────────────────────────────────────────────
DB["Biology"][1] = [
  { id:"bi1_1",  question:"The basic unit of life is the", options:{A:"Tissue",B:"Organ",C:"Cell",D:"Organism"}, answer:"C", explanation:"The cell is the basic structural, functional, and biological unit of all living organisms — the foundation of cell theory." },
  { id:"bi1_2",  question:"Which organelle is responsible for producing energy (ATP) in a cell?", options:{A:"Ribosome",B:"Nucleus",C:"Golgi apparatus",D:"Mitochondria"}, answer:"D", explanation:"Mitochondria are the 'powerhouse of the cell.' They produce ATP through cellular respiration — the Krebs cycle and oxidative phosphorylation." },
  { id:"bi1_3",  question:"The process by which green plants manufacture food using sunlight is called", options:{A:"Respiration",B:"Transpiration",C:"Photosynthesis",D:"Osmosis"}, answer:"C", explanation:"Photosynthesis: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂. Occurs in chloroplasts using chlorophyll." },
  { id:"bi1_4",  question:"Which blood group is known as the universal donor?", options:{A:"A",B:"AB",C:"B",D:"O"}, answer:"D", explanation:"Blood group O negative lacks A, B, and Rh antigens — so it can be given to any blood type without triggering an immune reaction." },
  { id:"bi1_5",  question:"Osmosis is best defined as the movement of", options:{A:"Solute molecules from low to high concentration",B:"Water molecules from high water potential to low water potential through a semi-permeable membrane",C:"All molecules from high to low concentration",D:"Water against a concentration gradient"}, answer:"B", explanation:"Osmosis is the passive movement of water from higher water potential to lower water potential through a selectively permeable membrane — no energy required." },
  { id:"bi1_6",  question:"The part of the brain controlling balance and coordination is the", options:{A:"Cerebrum",B:"Medulla oblongata",C:"Thalamus",D:"Cerebellum"}, answer:"D", explanation:"The cerebellum coordinates voluntary movements and maintains balance and posture. The cerebrum handles conscious thought; the medulla controls breathing and heartbeat." },
  { id:"bi1_7",  question:"Which enzyme digests starch in the mouth?", options:{A:"Pepsin",B:"Lipase",C:"Salivary amylase",D:"Trypsin"}, answer:"C", explanation:"Salivary amylase (ptyalin) breaks starch into maltose — beginning carbohydrate digestion. Pepsin digests proteins in the stomach. Trypsin digests proteins in the small intestine." },
  { id:"bi1_8",  question:"In humans, meiosis results in", options:{A:"Two diploid cells",B:"Four haploid cells",C:"Two haploid cells",D:"Four diploid cells"}, answer:"B", explanation:"Meiosis I and II produce four haploid gametes, each with half the chromosome number. When gametes fuse at fertilisation, the diploid number (2n = 46) is restored." },
  { id:"bi1_9",  question:"The site of gaseous exchange in humans is the", options:{A:"Trachea",B:"Bronchus",C:"Alveoli",D:"Diaphragm"}, answer:"C", explanation:"Alveoli are tiny air sacs in the lungs. Oxygen diffuses into blood capillaries; CO₂ diffuses out. Their thin walls and large surface area make them ideal for gaseous exchange." },
  { id:"bi1_10", question:"Which of the following is NOT a function of the skeleton?", options:{A:"Support",B:"Protection of vital organs",C:"Production of digestive enzymes",D:"Production of blood cells"}, answer:"C", explanation:"The skeleton supports, protects, enables movement, and produces blood cells in red bone marrow. Digestive enzymes are produced by the pancreas and stomach — not the skeleton." },
  { id:"bi1_11", question:"Insulin is produced by which organ?", options:{A:"Liver",B:"Kidney",C:"Adrenal gland",D:"Pancreas"}, answer:"D", explanation:"Insulin is produced by the beta cells of the islets of Langerhans in the pancreas. It lowers blood glucose. Deficiency causes diabetes mellitus." },
  { id:"bi1_12", question:"Which disease is caused by a protozoan?", options:{A:"Tuberculosis",B:"Malaria",C:"Measles",D:"Ringworm"}, answer:"B", explanation:"Malaria is caused by Plasmodium — a protozoan transmitted by the female Anopheles mosquito. TB = bacterium; Measles = virus; Ringworm = fungus." },
  { id:"bi1_13", question:"In a food chain, organisms that manufacture their own food are called", options:{A:"Consumers",B:"Decomposers",C:"Producers",D:"Herbivores"}, answer:"C", explanation:"Producers (autotrophs) — mainly green plants and algae — make their own food through photosynthesis and form the base of all food chains." },
  { id:"bi1_14", question:"The process of water loss through stomata of leaves is called", options:{A:"Osmosis",B:"Guttation",C:"Transpiration",D:"Translocation"}, answer:"C", explanation:"Transpiration is the evaporation of water through stomata. It drives the transpiration stream upward through xylem. Guttation is liquid water loss through hydathodes." },
  { id:"bi1_15", question:"Which characteristic is shared by ALL living organisms?", options:{A:"Photosynthesis",B:"Movement",C:"Respiration",D:"Reproduction"}, answer:"C", explanation:"All organisms carry out respiration to release energy from food. Not all photosynthesize, not all visibly move, and reproduction is not continuous at all times." },
  { id:"bi1_16", question:"The XY chromosome combination results in", options:{A:"A female",B:"Either male or female",C:"A male",D:"An intersex individual"}, answer:"C", explanation:"XX = female; XY = male. The Y chromosome carries the SRY gene triggering male development. Sperm determines offspring sex." },
  { id:"bi1_17", question:"Which part of the eye controls the amount of light entering?", options:{A:"Cornea",B:"Retina",C:"Iris",D:"Lens"}, answer:"C", explanation:"The iris controls pupil size — dilating in dim light, constricting in bright light. The retina detects light; the lens focuses light; the cornea refracts light." },
  { id:"bi1_18", question:"DNA is found mainly in the", options:{A:"Mitochondria",B:"Ribosome",C:"Nucleus",D:"Cell membrane"}, answer:"C", explanation:"Most DNA in eukaryotic cells is in the nucleus, organised into chromosomes. Small amounts exist in mitochondria and chloroplasts." },
  { id:"bi1_19", question:"Water and mineral salts are transported from roots to leaves through the", options:{A:"Phloem",B:"Cortex",C:"Epidermis",D:"Xylem"}, answer:"D", explanation:"Xylem transports water and minerals upward — driven by transpiration pull. Phloem transports organic solutes (sucrose) from leaves to all plant parts." },
  { id:"bi1_20", question:"Vitamins are important because they", options:{A:"Provide energy",B:"Build and repair body tissues",C:"Regulate body processes and prevent deficiency diseases",D:"Provide minerals"}, answer:"C", explanation:"Vitamins are micronutrients that regulate metabolism and prevent deficiency diseases — Vitamin C deficiency causes scurvy; Vitamin D deficiency causes rickets." },
  { id:"bi1_21", question:"A reflex action is best described as", options:{A:"A voluntary, conscious response",B:"A slow, deliberate brain response",C:"An automatic, involuntary response to a stimulus",D:"A learned behaviour"}, answer:"C", explanation:"A reflex action bypasses conscious brain control — impulse travels: receptor → sensory neurone → spinal cord → motor neurone → effector." },
  { id:"bi1_22", question:"The primary function of red blood cells is to", options:{A:"Fight infections",B:"Transport oxygen around the body",C:"Produce antibodies",D:"Assist in blood clotting"}, answer:"B", explanation:"Red blood cells contain haemoglobin which binds oxygen in the lungs and releases it to tissues. They have no nucleus in mammals — maximising haemoglobin space." },
  { id:"bi1_23", question:"Cell division producing two identical daughter cells is called", options:{A:"Meiosis",B:"Binary fission",C:"Mitosis",D:"Budding"}, answer:"C", explanation:"Mitosis produces two genetically identical diploid daughter cells — used for growth and repair. Meiosis produces haploid gametes." },
  { id:"bi1_24", question:"Which is an example of a mutualistic relationship?", options:{A:"A tick feeding on a dog",B:"Nitrogen-fixing bacteria in legume root nodules",C:"A tapeworm in the human intestine",D:"An orchid growing on a tree for support only"}, answer:"B", explanation:"Mutualism benefits BOTH organisms. Rhizobium bacteria fix nitrogen for the plant; the plant provides carbohydrates to the bacteria. Tick and tapeworm are parasites." },
  { id:"bi1_25", question:"Haemoglobin is important because it", options:{A:"Regulates blood pressure",B:"Carries oxygen from lungs to body tissues",C:"Produces antibodies",D:"Digests fats"}, answer:"B", explanation:"Haemoglobin reversibly binds oxygen in the lungs to form oxyhaemoglobin, releasing it where oxygen concentration is low." },
  { id:"bi1_26", question:"The role of decomposers in an ecosystem is to", options:{A:"Convert sunlight to chemical energy",B:"Consume primary producers",C:"Break down dead organic matter and recycle nutrients",D:"Fix atmospheric nitrogen"}, answer:"C", explanation:"Decomposers (bacteria and fungi) break down dead matter into inorganic compounds — returning minerals to the soil and driving nutrient cycles." },
  { id:"bi1_27", question:"Which vitamin is essential for blood clotting?", options:{A:"Vitamin A",B:"Vitamin B",C:"Vitamin C",D:"Vitamin K"}, answer:"D", explanation:"Vitamin K is needed for the synthesis of prothrombin and other clotting factors in the liver. Deficiency causes impaired clotting and excessive bleeding." },
  { id:"bi1_28", question:"Feeding on dead and decaying organic matter is called", options:{A:"Holozoic nutrition",B:"Parasitic nutrition",C:"Autotrophic nutrition",D:"Saprophytic nutrition"}, answer:"D", explanation:"Saprophytic nutrition involves secreting digestive enzymes externally onto dead matter and absorbing the products — used by fungi and many bacteria." },
  { id:"bi1_29", question:"When Tt × Tt plants are crossed, the phenotypic ratio of offspring is", options:{A:"1:2:1",B:"3 tall : 1 short",C:"1 tall : 1 short",D:"All tall"}, answer:"B", explanation:"Tt × Tt gives TT, Tt, Tt, tt — genotypic ratio 1:2:1. Since T is dominant, TT and Tt are tall, giving 3 tall : 1 short — Mendel's law of segregation." },
  { id:"bi1_30", question:"The correct pathway of food through the digestive system is", options:{A:"Mouth → Oesophagus → Stomach → Small intestine → Large intestine",B:"Mouth → Stomach → Oesophagus → Small intestine → Large intestine",C:"Mouth → Oesophagus → Small intestine → Stomach → Large intestine",D:"Mouth → Stomach → Small intestine → Oesophagus → Large intestine"}, answer:"A", explanation:"Mouth → Oesophagus (passage) → Stomach (protein digestion) → Small intestine (main digestion and absorption) → Large intestine (water absorption) → Rectum/Anus." },
  { id:"bi1_31", question:"Maintaining a stable internal environment despite external changes is called", options:{A:"Excretion",B:"Homeostasis",C:"Metabolism",D:"Thermoregulation"}, answer:"B", explanation:"Homeostasis maintains stable internal conditions (temperature, blood glucose, pH, water content) through negative feedback mechanisms." },
  { id:"bi1_32", question:"In ecology, a niche refers to", options:{A:"The physical location where an organism lives",B:"The role and position of an organism within its ecosystem",C:"The food an organism eats",D:"The relationship between two organisms"}, answer:"B", explanation:"An ecological niche is the role of an organism in its environment — what it eats, what eats it, and its environmental impact. A habitat is where it lives." },
  { id:"bi1_33", question:"In the chain Grass → Grasshopper → Frog → Snake → Eagle, the secondary consumer is", options:{A:"Grass",B:"Grasshopper",C:"Frog",D:"Snake"}, answer:"C", explanation:"Grass = producer; Grasshopper = primary consumer; Frog = secondary consumer; Snake = tertiary consumer; Eagle = quaternary consumer." },
  { id:"bi1_34", question:"Movement of substances from high to low concentration without energy is called", options:{A:"Active transport",B:"Osmosis",C:"Facilitated diffusion",D:"Diffusion"}, answer:"D", explanation:"Diffusion is passive movement down a concentration gradient — no ATP required. Active transport moves substances against a gradient and requires energy." },
  { id:"bi1_35", question:"Which is an example of an endocrine gland?", options:{A:"Salivary gland",B:"Sweat gland",C:"Adrenal gland",D:"Tear gland"}, answer:"C", explanation:"Endocrine glands are ductless — they secrete hormones directly into the bloodstream. The adrenal gland secretes adrenaline and cortisol. Salivary, sweat, and tear glands are exocrine." },
  { id:"bi1_36", question:"The Aedes mosquito is the vector of", options:{A:"Malaria",B:"Sleeping sickness",C:"Yellow fever",D:"Filariasis"}, answer:"C", explanation:"Aedes aegypti transmits Yellow fever, Dengue, and Zika. Anopheles transmits malaria. Tsetse fly transmits sleeping sickness. Culex transmits filariasis." },
  { id:"bi1_37", question:"The function of stomata in plants is", options:{A:"Absorption of water from soil",B:"Transport of food to all parts",C:"Gaseous exchange and regulation of water loss",D:"Production of chlorophyll"}, answer:"C", explanation:"Stomata are pores on leaf surfaces surrounded by guard cells. They allow CO₂ in and O₂ out during photosynthesis, and regulate water loss by opening and closing." },
  { id:"bi1_38", question:"Converting atmospheric nitrogen into a form usable by plants is called", options:{A:"Denitrification",B:"Nitrification",C:"Nitrogen fixation",D:"Ammonification"}, answer:"C", explanation:"Nitrogen fixation converts N₂ into ammonia — carried out by Rhizobium (in legume roots) and Azotobacter (free-living in soil)." },
  { id:"bi1_39", question:"Which correctly represents a food web?", options:{A:"Sun → Grass → Cow → Human",B:"Grass → Rabbit → Fox and Grass → Grasshopper → Frog → Fox",C:"Human → Cow → Grass → Sun",D:"Rabbit → Fox → Grass"}, answer:"B", explanation:"A food web is multiple interconnected food chains. Option B shows two chains sharing a consumer (Fox) — a true web." },
  { id:"bi1_40", question:"Antiseptics differ from antibiotics in that antiseptics", options:{A:"Treat bacterial infections inside the body",B:"Kill viruses only",C:"Are applied externally to prevent microbial growth on body surfaces",D:"Can only be obtained on prescription"}, answer:"C", explanation:"Antiseptics are applied to skin/wounds externally (e.g. iodine solution). Antibiotics are taken internally to treat bacterial infections." }
]; // end Biology


// ── CHEMISTRY ────────────────────────────────────────────────
DB["Chemistry"][1] = [
  { id:"ch1_1",  question:"Which of the following is a physical change?", options:{A:"Burning of wood",B:"Rusting of iron",C:"Melting of ice",D:"Souring of milk"}, answer:"C", explanation:"Melting of ice is a physical change — only the state changes (solid → liquid); the chemical composition (H₂O) remains the same." },
  { id:"ch1_2",  question:"The atomic number of an element is determined by the number of", options:{A:"Neutrons",B:"Protons",C:"Electrons and neutrons",D:"Nucleons"}, answer:"B", explanation:"Atomic number = number of protons in the nucleus. It uniquely identifies the element. In a neutral atom, number of electrons = number of protons." },
  { id:"ch1_3",  question:"Which gas is produced when dilute hydrochloric acid reacts with zinc?", options:{A:"Oxygen",B:"Carbon dioxide",C:"Chlorine",D:"Hydrogen"}, answer:"D", explanation:"Zn + 2HCl → ZnCl₂ + H₂↑. Hydrogen gas is produced — it burns with a squeaky pop when a lighted splint is applied." },
  { id:"ch1_4",  question:"The pH of a neutral solution is", options:{A:"0",B:"7",C:"14",D:"1"}, answer:"B", explanation:"pH 7 = neutral (pure water at 25°C). pH < 7 = acidic; pH > 7 = alkaline." },
  { id:"ch1_5",  question:"Which of the following is NOT a noble gas?", options:{A:"Neon",B:"Argon",C:"Nitrogen",D:"Helium"}, answer:"C", explanation:"Noble gases (Group 18): Helium, Neon, Argon, Krypton, Xenon, Radon. Nitrogen is in Group 15 — it is a diatomic gas (N₂), not a noble gas." },
  { id:"ch1_6",  question:"The process by which a solid changes directly to a gas without passing through a liquid state is called", options:{A:"Evaporation",B:"Condensation",C:"Sublimation",D:"Melting"}, answer:"C", explanation:"Sublimation: solid → gas directly. Examples: dry ice (solid CO₂), iodine, naphthalene." },
  { id:"ch1_7",  question:"Alloys are formed by mixing", options:{A:"A metal with a non-metal compound",B:"Two or more metals (or a metal with a non-metal) to improve properties",C:"Two non-metals",D:"An element with a molecule"}, answer:"B", explanation:"An alloy is a mixture of two or more metals, or a metal with a non-metal. Examples: Brass (Cu + Zn), Steel (Fe + C), Bronze (Cu + Sn)." },
  { id:"ch1_8",  question:"Which of the following is a mixture?", options:{A:"Water (H₂O)",B:"Salt (NaCl)",C:"Air",D:"Carbon dioxide (CO₂)"}, answer:"C", explanation:"Air is a mixture of gases (N₂ ~78%, O₂ ~21%, Ar ~1%, CO₂ ~0.04%) — not chemically combined." },
  { id:"ch1_9",  question:"In electrolysis, reduction occurs at the", options:{A:"Anode",B:"Cathode",C:"Electrolyte",D:"Salt bridge"}, answer:"B", explanation:"At the cathode (negative electrode): positive ions (cations) gain electrons → reduction. OIL RIG: Oxidation Is Loss, Reduction Is Gain." },
  { id:"ch1_10", question:"The formula for sulphuric acid is", options:{A:"HCl",B:"HNO₃",C:"H₂SO₄",D:"H₃PO₄"}, answer:"C", explanation:"H₂SO₄ = sulphuric acid. HCl = hydrochloric acid; HNO₃ = nitric acid; H₃PO₄ = phosphoric acid." },
  { id:"ch1_11", question:"Which property allows water to dissolve many ionic compounds?", options:{A:"Its low boiling point",B:"Its high density",C:"Its polar nature",D:"Its colourless appearance"}, answer:"C", explanation:"Water is a polar molecule. This polarity allows it to attract and surround ions — separating them from the ionic lattice." },
  { id:"ch1_12", question:"The process used to separate a mixture of liquids with different boiling points is", options:{A:"Filtration",B:"Crystallisation",C:"Distillation",D:"Chromatography"}, answer:"C", explanation:"Distillation separates liquids based on different boiling points — the liquid with the lower boiling point vaporises first." },
  { id:"ch1_13", question:"Which of the following is an example of an exothermic reaction?", options:{A:"Melting of ice",B:"Dissolution of ammonium nitrate in water",C:"Combustion of methane",D:"Photosynthesis"}, answer:"C", explanation:"Combustion of methane (CH₄ + 2O₂ → CO₂ + 2H₂O) releases heat — it is exothermic. Melting ice and dissolving ammonium nitrate absorb heat (endothermic)." },
  { id:"ch1_14", question:"The element with the electronic configuration 2, 8, 7 belongs to Group", options:{A:"I",B:"VII",C:"VI",D:"0"}, answer:"B", explanation:"The outermost shell has 7 electrons → Group VII (halogens). The element has 17 protons — it is Chlorine (Cl)." },
  { id:"ch1_15", question:"Hydrocarbons contain only", options:{A:"Hydrogen and nitrogen",B:"Carbon and oxygen",C:"Hydrogen and carbon",D:"Carbon, hydrogen and oxygen"}, answer:"C", explanation:"By definition, hydrocarbons contain only carbon and hydrogen. Alkanes, alkenes, and alkynes are all hydrocarbons." },
  { id:"ch1_16", question:"Rusting of iron requires", options:{A:"Only water",B:"Only oxygen",C:"Both oxygen and water",D:"Carbon dioxide and water"}, answer:"C", explanation:"Rusting requires both water and oxygen simultaneously. Iron in dry air or deoxygenated water alone does not rust." },
  { id:"ch1_17", question:"Which of the following is a strong acid?", options:{A:"Ethanoic acid",B:"Citric acid",C:"Hydrochloric acid",D:"Carbonic acid"}, answer:"C", explanation:"HCl is a strong acid — it fully ionises in water. Ethanoic acid, citric acid, and carbonic acid are weak acids — they only partially ionise." },
  { id:"ch1_18", question:"The law of conservation of mass states that", options:{A:"Matter can be created in chemical reactions",B:"Total mass of reactants equals total mass of products in a chemical reaction",C:"Energy is conserved in all reactions",D:"Atoms are destroyed during combustion"}, answer:"B", explanation:"Mass is neither created nor destroyed in a chemical reaction. Attributed to Antoine Lavoisier." },
  { id:"ch1_19", question:"Which gas turns limewater milky?", options:{A:"Oxygen",B:"Hydrogen",C:"Carbon dioxide",D:"Nitrogen"}, answer:"C", explanation:"CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O. The white precipitate of calcium carbonate turns limewater milky — the standard test for carbon dioxide." },
  { id:"ch1_20", question:"An isotope of an element differs from another isotope in its", options:{A:"Number of protons",B:"Atomic number",C:"Number of neutrons",D:"Electronic configuration"}, answer:"C", explanation:"Isotopes have the same atomic number (same protons) but different mass numbers — due to different numbers of neutrons. E.g. Carbon-12 and Carbon-14." },
  { id:"ch1_21", question:"The type of bonding in sodium chloride (NaCl) is", options:{A:"Covalent",B:"Metallic",C:"Ionic",D:"Hydrogen bonding"}, answer:"C", explanation:"NaCl forms by electron transfer from Na to Cl, creating Na⁺ and Cl⁻ ions held together by electrostatic attraction — ionic bonding." },
  { id:"ch1_22", question:"Which of the following is the correct chemical formula for glucose?", options:{A:"C₆H₁₂O₆",B:"C₁₂H₂₂O₁₁",C:"CH₄",D:"C₂H₅OH"}, answer:"A", explanation:"Glucose = C₆H₁₂O₆. Sucrose = C₁₂H₂₂O₁₁. Methane = CH₄. Ethanol = C₂H₅OH." },
  { id:"ch1_23", question:"The indicator that turns red in acid and blue in alkali is", options:{A:"Methyl orange",B:"Phenolphthalein",C:"Litmus",D:"Universal indicator"}, answer:"C", explanation:"Litmus turns red in acid and blue in alkali. Methyl orange turns red in acid and yellow in alkali. Phenolphthalein is colourless in acid and pink in alkali." },
  { id:"ch1_24", question:"Which reaction describes neutralisation?", options:{A:"Metal + water → metal hydroxide + hydrogen",B:"Acid + base → salt + water",C:"Metal + acid → salt + hydrogen",D:"Oxide + water → acid"}, answer:"B", explanation:"Neutralisation: acid + base → salt + water. E.g. HCl + NaOH → NaCl + H₂O." },
  { id:"ch1_25", question:"Petroleum is separated into its components by", options:{A:"Simple distillation",B:"Fractional distillation",C:"Filtration",D:"Chromatography"}, answer:"B", explanation:"Fractional distillation separates crude oil into fractions (petrol, kerosene, diesel) based on their different boiling points in a fractionating column." },
  { id:"ch1_26", question:"Which of the following elements is a halogen?", options:{A:"Sodium",B:"Sulphur",C:"Bromine",D:"Potassium"}, answer:"C", explanation:"Halogens are Group VII elements: Fluorine, Chlorine, Bromine, Iodine, Astatine. Bromine is the only liquid halogen at room temperature." },
  { id:"ch1_27", question:"The molar mass of water (H₂O) is approximately", options:{A:"16 g/mol",B:"18 g/mol",C:"20 g/mol",D:"12 g/mol"}, answer:"B", explanation:"H₂O: (2 × 1) + 16 = 18 g/mol." },
  { id:"ch1_28", question:"A catalyst in a chemical reaction", options:{A:"Is consumed during the reaction",B:"Increases the activation energy",C:"Speeds up the reaction without being permanently changed",D:"Changes the products of the reaction"}, answer:"C", explanation:"A catalyst lowers the activation energy, increasing reaction rate. It is not consumed and can be recovered unchanged. E.g. iron in the Haber process." },
  { id:"ch1_29", question:"Which of the following is an alkali metal?", options:{A:"Calcium",B:"Magnesium",C:"Sodium",D:"Aluminium"}, answer:"C", explanation:"Alkali metals are Group I: Lithium, Sodium, Potassium, Rubidium, Caesium, Francium. They have one electron in their outer shell and are highly reactive." },
  { id:"ch1_30", question:"The reaction between an acid and a carbonate produces", options:{A:"Salt and water",B:"Salt, water and carbon dioxide",C:"Salt and hydrogen",D:"Oxide and water"}, answer:"B", explanation:"Acid + carbonate → salt + water + CO₂. E.g. 2HCl + CaCO₃ → CaCl₂ + H₂O + CO₂↑." },
  { id:"ch1_31", question:"Which of the following describes a saturated hydrocarbon?", options:{A:"It contains a carbon-carbon double bond",B:"It contains only single carbon-carbon bonds",C:"It contains a carbon-carbon triple bond",D:"It contains a benzene ring"}, answer:"B", explanation:"Saturated hydrocarbons (alkanes) contain only single C-C bonds. Unsaturated hydrocarbons contain double (alkenes) or triple (alkynes) bonds." },
  { id:"ch1_32", question:"The main ore of aluminium is", options:{A:"Haematite",B:"Galena",C:"Bauxite",D:"Malachite"}, answer:"C", explanation:"Bauxite (Al₂O₃·2H₂O) is the principal ore of aluminium. Haematite is iron ore; Galena is lead ore; Malachite is copper ore." },
  { id:"ch1_33", question:"In the Periodic Table, elements in the same GROUP have the same", options:{A:"Mass number",B:"Number of electron shells",C:"Number of electrons in the outermost shell",D:"Atomic mass"}, answer:"C", explanation:"Elements in the same group have the same number of valence electrons — giving them similar chemical properties." },
  { id:"ch1_34", question:"Which gas is produced at the anode during electrolysis of dilute sulphuric acid?", options:{A:"Hydrogen",B:"Oxygen",C:"Sulphur dioxide",D:"Carbon dioxide"}, answer:"B", explanation:"At the anode during electrolysis of dilute H₂SO₄, OH⁻ ions are oxidised: 4OH⁻ → 2H₂O + O₂↑. Oxygen at anode; hydrogen at cathode." },
  { id:"ch1_35", question:"The empirical formula of a compound shows", options:{A:"The actual number of atoms in one molecule",B:"The simplest whole number ratio of atoms present",C:"The structural arrangement of atoms",D:"The molecular mass of the compound"}, answer:"B", explanation:"The empirical formula gives the simplest ratio of atoms. E.g. glucose (C₆H₁₂O₆) has empirical formula CH₂O." },
  { id:"ch1_36", question:"Which of the following is a property of metals?", options:{A:"They are generally poor conductors of electricity",B:"They are generally brittle",C:"They have high melting points and conduct electricity",D:"They have low densities and are non-lustrous"}, answer:"C", explanation:"Metals are good conductors of heat and electricity, have high melting points, are malleable, ductile, and have a metallic lustre." },
  { id:"ch1_37", question:"Fermentation of glucose produces", options:{A:"Methane and water",B:"Carbon dioxide and ethanol",C:"Acetic acid and hydrogen",D:"Lactic acid only"}, answer:"B", explanation:"C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂. Yeast converts glucose into ethanol and carbon dioxide — the basis of brewing." },
  { id:"ch1_38", question:"Which of the following is a greenhouse gas?", options:{A:"Nitrogen",B:"Oxygen",C:"Carbon dioxide",D:"Argon"}, answer:"C", explanation:"Carbon dioxide (CO₂), methane (CH₄), and water vapour are major greenhouse gases. They absorb infrared radiation and trap heat in the atmosphere." },
  { id:"ch1_39", question:"The process of zinc coating on iron to prevent rusting is called", options:{A:"Anodising",B:"Electroplating",C:"Galvanisation",D:"Alloying"}, answer:"C", explanation:"Galvanisation involves coating iron/steel with zinc. Zinc acts as a sacrificial anode, corroding preferentially and protecting the iron." },
  { id:"ch1_40", question:"An element has 11 protons and 12 neutrons. Its mass number is", options:{A:"11",B:"12",C:"23",D:"1"}, answer:"C", explanation:"Mass number = protons + neutrons = 11 + 12 = 23. This element is sodium (Na-23)." }
]; // end Chemistry


// ── PHYSICS ──────────────────────────────────────────────────
DB["Physics"][1] = [
  { id:"ph1_1",  question:"The SI unit of force is the", options:{A:"Watt",B:"Joule",C:"Newton",D:"Pascal"}, answer:"C", explanation:"The Newton (N) is the SI unit of force — the force needed to accelerate 1 kg at 1 m/s². Watt = power; Joule = energy; Pascal = pressure." },
  { id:"ph1_2",  question:"Which of the following is a vector quantity?", options:{A:"Speed",B:"Mass",C:"Temperature",D:"Velocity"}, answer:"D", explanation:"Vectors have both magnitude and direction. Velocity specifies both speed and direction. Speed, mass, and temperature are scalars." },
  { id:"ph1_3",  question:"A body is in equilibrium when", options:{A:"It is moving at constant speed only",B:"The net force and net torque acting on it are both zero",C:"It is stationary only",D:"Equal forces act on it from opposite sides"}, answer:"B", explanation:"Equilibrium requires: (1) net force = 0 and (2) net torque = 0. A body moving at constant velocity satisfies condition 1 — dynamic equilibrium." },
  { id:"ph1_4",  question:"The formula for calculating pressure is", options:{A:"P = mv",B:"P = F × A",C:"P = F/A",D:"P = W/t"}, answer:"C", explanation:"Pressure = Force ÷ Area. SI unit: Pascal (Pa) = N/m². P = mv is momentum; P = W/t is power." },
  { id:"ph1_5",  question:"Newton's first law of motion states that", options:{A:"Force equals mass times acceleration",B:"Every action has an equal and opposite reaction",C:"A body remains at rest or in uniform motion unless acted upon by an external force",D:"The rate of change of momentum is proportional to the applied force"}, answer:"C", explanation:"Newton's First Law (Law of Inertia): a body at rest stays at rest; a body in motion stays in uniform motion in a straight line — unless an external net force acts on it." },
  { id:"ph1_6",  question:"The speed of light in a vacuum is approximately", options:{A:"3.0 × 10⁶ m/s",B:"3.0 × 10⁸ m/s",C:"3.0 × 10¹⁰ m/s",D:"3.0 × 10⁴ m/s"}, answer:"B", explanation:"c = 3.0 × 10⁸ m/s — the cosmic speed limit. Used in Einstein's equation E = mc²." },
  { id:"ph1_7",  question:"Which correctly states Ohm's Law?", options:{A:"Resistance = Current × Voltage",B:"Current = Voltage × Resistance",C:"Voltage = Current × Resistance",D:"Power = Current × Resistance"}, answer:"C", explanation:"Ohm's Law: V = IR. Current through a conductor is directly proportional to voltage across it at constant temperature." },
  { id:"ph1_8",  question:"The unit of electrical resistance is the", options:{A:"Ampere",B:"Volt",C:"Watt",D:"Ohm"}, answer:"D", explanation:"Resistance is measured in Ohms (Ω). Ampere = current; Volt = potential difference; Watt = power." },
  { id:"ph1_9",  question:"Which type of wave requires a material medium to travel?", options:{A:"Radio waves",B:"Light waves",C:"Sound waves",D:"X-rays"}, answer:"C", explanation:"Sound is a mechanical longitudinal wave — it needs a medium (solid, liquid, or gas). It cannot travel through a vacuum." },
  { id:"ph1_10", question:"Light bending as it passes from one medium to another is called", options:{A:"Reflection",B:"Refraction",C:"Diffraction",D:"Dispersion"}, answer:"B", explanation:"Refraction occurs because light changes speed as it crosses the boundary between media of different optical densities." },
  { id:"ph1_11", question:"The formula for kinetic energy is", options:{A:"KE = mgh",B:"KE = ½mv²",C:"KE = mv",D:"KE = Fs"}, answer:"B", explanation:"KE = ½mv² where m = mass (kg) and v = velocity (m/s). mgh = gravitational potential energy; mv = momentum." },
  { id:"ph1_12", question:"Heat transferred through a vacuum is by", options:{A:"Conduction",B:"Convection",C:"Radiation",D:"Evaporation"}, answer:"C", explanation:"Radiation transfers heat as electromagnetic (infrared) waves — no medium needed. Conduction needs direct contact; convection needs a fluid medium." },
  { id:"ph1_13", question:"A car accelerates from rest to 20 m/s in 4 seconds. Its acceleration is", options:{A:"80 m/s²",B:"5 m/s²",C:"0.2 m/s²",D:"16 m/s²"}, answer:"B", explanation:"a = (v − u)/t = (20 − 0)/4 = 5 m/s²." },
  { id:"ph1_14", question:"The law of conservation of energy states that", options:{A:"Energy is always lost as heat",B:"Energy can be created under special conditions",C:"Energy can neither be created nor destroyed — only converted from one form to another",D:"Kinetic energy always equals potential energy"}, answer:"C", explanation:"Total energy of an isolated system is constant. Energy transforms but is never created or destroyed." },
  { id:"ph1_15", question:"The unit of power is the", options:{A:"Joule",B:"Newton",C:"Watt",D:"Pascal"}, answer:"C", explanation:"Power is measured in Watts (W). P = W/t. 1 Watt = 1 Joule per second." },
  { id:"ph1_16", question:"A concave mirror is used in", options:{A:"Rear-view mirrors in cars",B:"Shop security mirrors",C:"Torches and searchlights",D:"Periscopes"}, answer:"C", explanation:"Concave mirrors converge parallel rays to a focal point — producing a focused beam in torches and searchlights. Convex mirrors are used in rear-view and security mirrors." },
  { id:"ph1_17", question:"Which particle has negligible mass and carries a negative charge?", options:{A:"Proton",B:"Neutron",C:"Alpha particle",D:"Electron"}, answer:"D", explanation:"Electrons have negligible mass (9.11 × 10⁻³¹ kg) and charge of −1. Protons: mass, +1. Neutrons: mass, 0." },
  { id:"ph1_18", question:"Archimedes' principle states that", options:{A:"Pressure increases with depth in a fluid",B:"A body immersed in a fluid experiences an upthrust equal to the weight of fluid displaced",C:"Volume of a gas is inversely proportional to its pressure",D:"An object floats when its density is less than the fluid"}, answer:"B", explanation:"Upthrust = weight of fluid displaced. This explains why ships float and is the basis of buoyancy calculations." },
  { id:"ph1_19", question:"Frequency is related to period by", options:{A:"f = T²",B:"f = 1/T",C:"f = T/2",D:"f = 2T"}, answer:"B", explanation:"f = 1/T. If T = 0.5 s, f = 2 Hz. Wave equation: v = fλ." },
  { id:"ph1_20", question:"The moment of a force is", options:{A:"The product of force and the perpendicular distance from the pivot",B:"The ratio of force to distance",C:"The product of mass and acceleration",D:"The rate of change of kinetic energy"}, answer:"A", explanation:"Moment = F × d. Unit: Newton-metre (N·m). Greater force or greater distance from pivot = greater turning effect." },
  { id:"ph1_21", question:"A transverse wave is one where", options:{A:"Particles vibrate parallel to wave travel",B:"Particles vibrate perpendicular to wave travel",C:"The wave can only travel through solids",D:"The wave transfers matter"}, answer:"B", explanation:"Transverse waves: particles oscillate at right angles to propagation. Examples: light, water waves. Longitudinal waves: particles vibrate parallel — example: sound." },
  { id:"ph1_22", question:"A radioactive nucleus emitting a helium nucleus undergoes", options:{A:"Beta decay",B:"Gamma emission",C:"Alpha decay",D:"Nuclear fission"}, answer:"C", explanation:"Alpha decay emits ⁴₂He (2p + 2n). Parent nucleus loses 2 from atomic number and 4 from mass number. Alpha is least penetrating but most ionising." },
  { id:"ph1_23", question:"A pendulum completes 20 oscillations in 40 seconds. Its frequency is", options:{A:"0.5 Hz",B:"2 Hz",C:"800 Hz",D:"20 Hz"}, answer:"A", explanation:"f = oscillations ÷ time = 20 ÷ 40 = 0.5 Hz. T = 40/20 = 2 s. f = 1/T = 0.5 Hz." },
  { id:"ph1_24", question:"The image formed by a plane mirror is", options:{A:"Real, inverted, and magnified",B:"Real, upright, and same size",C:"Virtual, upright, and same size as the object",D:"Virtual, inverted, and diminished"}, answer:"C", explanation:"Plane mirror image: Virtual, Upright, Same size, Laterally inverted. It appears as far behind the mirror as the object is in front." },
  { id:"ph1_25", question:"Work done by a force is calculated as", options:{A:"W = m × a",B:"W = F × d × cos θ",C:"W = ½mv²",D:"W = Pt"}, answer:"B", explanation:"W = Fd cos θ. When force and displacement are parallel (θ = 0°), W = Fd. No work is done when force is perpendicular to displacement." },
  { id:"ph1_26", question:"Which electromagnetic radiation has the shortest wavelength?", options:{A:"Radio waves",B:"Visible light",C:"Infrared radiation",D:"Gamma rays"}, answer:"D", explanation:"EM spectrum in order of increasing wavelength: Gamma → X-rays → Ultraviolet → Visible → Infrared → Microwaves → Radio. Gamma rays have shortest wavelength and highest energy." },
  { id:"ph1_27", question:"Change of state from liquid to gas at fixed temperature and pressure is called", options:{A:"Evaporation",B:"Sublimation",C:"Condensation",D:"Boiling"}, answer:"D", explanation:"Boiling occurs throughout the liquid at the boiling point. Evaporation occurs only at the surface at any temperature." },
  { id:"ph1_28", question:"An object of mass 5 kg — what is its weight? (g = 10 m/s²)", options:{A:"5 N",B:"0.5 N",C:"50 N",D:"500 N"}, answer:"C", explanation:"W = mg = 5 × 10 = 50 N. Weight is a force (Newtons), not mass (kg)." },
  { id:"ph1_29", question:"Lenz's law states the induced current always", options:{A:"Maximises the inducing change",B:"Opposes the change that caused it",C:"Flows in the same direction as primary current",D:"Increases magnetic flux"}, answer:"B", explanation:"Lenz's Law: induced EMF opposes the change in magnetic flux that produced it — a consequence of energy conservation." },
  { id:"ph1_30", question:"The unit of electric charge is the", options:{A:"Ampere",B:"Volt",C:"Coulomb",D:"Ohm"}, answer:"C", explanation:"Charge is measured in Coulombs (C). Q = It (1 C = 1 A × 1 s). Charge of one electron = 1.6 × 10⁻¹⁹ C." },
  { id:"ph1_31", question:"The principle of moments states that for equilibrium", options:{A:"Sum of all forces = zero",B:"Sum of clockwise moments = sum of anticlockwise moments about any pivot",C:"Net torque = mass × angular acceleration",D:"All forces are equal in magnitude"}, answer:"B", explanation:"Clockwise moments = anticlockwise moments about any pivot point. This is the basis for all lever calculations." },
  { id:"ph1_32", question:"A transformer", options:{A:"Converts AC to DC",B:"Converts DC to AC",C:"Changes the voltage of an AC supply",D:"Stores electrical energy"}, answer:"C", explanation:"Transformers step voltage up or down using electromagnetic induction. They only work with AC — not DC." },
  { id:"ph1_33", question:"Specific heat capacity is the heat energy needed to", options:{A:"Melt 1 kg of the substance",B:"Raise the temperature of 1 kg by 1°C",C:"Convert 1 kg of liquid to gas",D:"Change the state of 1 kg"}, answer:"B", explanation:"Q = mcΔT. Water's specific heat capacity is 4,200 J/kg/K — one of the highest of any common substance." },
  { id:"ph1_34", question:"Total internal reflection is applied in", options:{A:"Formation of a rainbow",B:"Operation of optical fibres",C:"Focusing of light by a convex lens",D:"Formation of shadows"}, answer:"B", explanation:"Optical fibres use total internal reflection to transmit light signals over long distances with minimal loss." },
  { id:"ph1_35", question:"A ball thrown vertically upward — at the highest point, its velocity is", options:{A:"At maximum",B:"Equal to initial velocity",C:"Zero",D:"Negative"}, answer:"C", explanation:"At the highest point the ball momentarily stops — velocity = zero. But gravitational acceleration continues to act downward." },
  { id:"ph1_36", question:"Power dissipated in a resistor is", options:{A:"P = V/I",B:"P = I²R",C:"P = IR²",D:"P = V²/I"}, answer:"B", explanation:"P = IV = I²R = V²/R. P = I²R is used when current and resistance are known. Unit: Watt." },
  { id:"ph1_37", question:"The critical angle is the angle of incidence at which the angle of refraction is", options:{A:"0°",B:"45°",C:"90°",D:"180°"}, answer:"C", explanation:"At the critical angle, the refracted ray travels exactly along the boundary (refraction angle = 90°). Beyond it, total internal reflection occurs." },
  { id:"ph1_38", question:"The amplitude of a wave is", options:{A:"The number of complete waves per second",B:"The distance between two consecutive crests",C:"The maximum displacement of a particle from its equilibrium position",D:"The speed of the wave"}, answer:"C", explanation:"Amplitude = maximum displacement from rest position. Greater amplitude means more energy carried." },
  { id:"ph1_39", question:"In nuclear fission", options:{A:"Two light nuclei combine to form a heavier nucleus",B:"A heavy nucleus splits into two smaller nuclei releasing energy",C:"A nucleus emits only an alpha particle",D:"Electrons are stripped from atoms by high temperatures"}, answer:"B", explanation:"Fission splits heavy nuclei (U-235) when struck by neutrons, releasing enormous energy and more neutrons — enabling a chain reaction." },
  { id:"ph1_40", question:"A machine has velocity ratio 5 and efficiency 80%. Its mechanical advantage is", options:{A:"4",B:"6.25",C:"0.25",D:"25"}, answer:"A", explanation:"MA = (Efficiency × VR) ÷ 100 = (80 × 5) ÷ 100 = 4. Mechanical advantage tells how much a machine multiplies the input force." }
]; // end Physics